### ISSUE TITLE
Filter user input

### ISSUE THREAD

**Issue by Voyager-12** [austinxewell/git-n-shape#17]
* Ensure that target body parts are generated for workouts
* Filter generated recipes by daily calorie goals

**Comment by CorySlsbry** [comment]
Redesigned nutrition menu to target diet. The nutrition button now returns recipes selected by the user. 

Targeting body parts via drop down menu is now functioning. Targeting body parts will now only display workouts for selection option for the entire entire week. This can be addressed in future releases.
